apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-docker-registry/backend-image:latest # Replace with your FastAPI app image
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "sqlite:///app/db/database.db"  # SQLite path inside the container
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP  # Internal communication between frontend and backend
