apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: docker pull sandydocker19/backend-app:8
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "sqlite:///app/db/database.db"  # SQLite path inside the container
